version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: concordcrm_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: concordcrm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: concordcrm
      MYSQL_USER: concorduser
      MYSQL_PASSWORD: concordpass
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: nginx:latest
    container_name: concordcrm_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
